base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('' , views.predict , name="predict"),
    path('results/' , views.results , name="results")
]

spam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('base.urls'))
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
import pickle
from django.shortcuts import render

path_model = "static/predictors/NaiveBayes_model.pkl"
path_vectorizer = "static/predictors/vectorizer.pkl"

with open(path_vectorizer, 'rb') as f:
    vectorizer = pickle.load(f)

with open(path_model, 'rb') as f:
    model = pickle.load(f)

# Create your views here.
def predict(request):
    return render(request , 'base/predict.html')

def results(request):
    if request.method == "GET":
        Email_text = request.GET.get('Email')
        # print(Email_text)
        text = [Email_text]
        X = vectorizer.transform(text)
        ans = model.predict(X)

        context = {'ans' : ans , 'Email' : Email_text}
    else:
        context = {'ans' : -1 , 'Email' : Email_text}

    return render(request , 'base/results.html' , context=context)

base/templates/base/predict.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block title %}
    Spam Detector
{% endblock title %}

{% block content %}
    <div class="form-container">
        <h1 class="heading"> Email Spam Detector </h1>
        
        <form action={% url "base:results" %} method="GET">
            {% csrf_token %}
            <label for="Email">Enter your Email:</label><br><br>
            <textarea id="Email" name="Email" rows="10" cols="50" placeholder="Write your Email here..." required></textarea><br><br>
            <input type="submit" value="Submit" class="submit-btn">
        </form>
    </div>
{% endblock content %}

base/templates/base/results.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block title %}
    Results
{% endblock title %}


{% block content %}
    <div class="result-container">
        <h1 class="heading">
            Results
        </h1>

        {% if ans == -1 %}
            <div class="result-text">Some error occurred</div>
            <div class="result-text"> Please try entering the data again</div>
        {% else %}
            <div class="result-text"> The email that you provided: </div>
            <p class="email-text"> {{Email}} </p>
            {% if ans == 1 %}
                <div class="result-text"> is a Spam </div>
            {% else %}
                <div class="result-text"> is not a Spam </div>
            {% endif %}
        {% endif %}

        <a href="{% url "base:predict" %}" class="reset-btn"> Check another Email </a>
    </div>
        

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <link rel="stylesheet" href={% static "css/style.css" %} >
    {% block css %}


    {% endblock css %}
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>